import { throwInvalidError } from "../errors";

export const failAction = () => throwInvalidError();
